# -*- coding: utf-8 -*-
"""互联网热梗种子词表（手工整理，先保证质量，后续用萌娘百科正文扩充）"""

# 每条结构：
# name=梗名, aliases=别名, meaning=含义, origin=出处/背景, usage=用法/场景, example=例句, category=分类
SEED = [
    {"name": "老六", "aliases": ["老六玩家"], "category": "游戏", "meaning": "指游戏里不跟队友打配合、躲在暗处偷袭的玩家，也泛指不讲武德、阴人的人。", "origin": "出自 CSGO 的自由人战术，自由人像队伍之外的第六人，后贬义化。", "usage": "形容队友/对手偷偷阴人、玩阴的。", "example": "刚才那个老六蹲墙角阴了我一整局", "related": ["自由人", "不讲武德"]},
    {"name": "鸡你太美", "aliases": ["只因你太美", "只因"], "category": "音乐/偶像", "meaning": "《只因你太美》听成“鸡你太美”的空耳梗，常用来玩蔡徐坤的梗。", "origin": "蔡徐坤在选秀节目中的自我介绍唱跳片段，网友空耳。", "usage": "调侃/玩梗时引用，常配合篮球和背带裤梗。", "example": "音乐一响，脑子里全是鸡你太美", "related": ["蔡徐坤", "背带裤"]},
    {"name": "6", "aliases": ["666", "溜"], "category": "通用", "meaning": "表示厉害、牛、操作帅，源自游戏连杀音效“hexakill”或谐音“溜”。", "origin": "网游玩家常用，后扩散全网。", "usage": "看到神操作或无语操作都可以刷。", "example": "这波操作我只能扣个6", "related": ["牛", "厉害"]},
    {"name": "尊嘟假嘟", "aliases": ["尊嘟假嘟O.o"], "category": "卖萌", "meaning": "“真的假的”的可爱谐音，带一丝阴阳怪气。", "origin": "网络流行语，常见于短视频评论区。", "usage": "对夸张说法表示怀疑或卖萌。", "example": "尊嘟假嘟？我不信", "related": ["真的假的"]},
    {"name": "公主请上车", "aliases": ["公主请上车"], "category": "网络段子", "meaning": "宠溺式邀请别人上车的梗，后扩展到各种“请XX”句式。", "origin": "短视频段子，男生对女生说“公主请上车”走红。", "usage": "对亲近的人开玩笑式献殷勤，也能反讽。", "example": "公主请上车，今天去哪都可", "related": ["王子请上车"]},
    {"name": "家人们谁懂啊", "aliases": ["谁懂啊"], "category": "吐槽", "meaning": "开麦吐槽的口头禅，表示某种离谱经历求共鸣。", "origin": "短视频博主常用开场，后成万用吐槽句式。", "usage": "讲糟心事前先来一句，拉近吐槽氛围。", "example": "家人们谁懂啊，电脑更新又把我搞崩了", "related": ["谁懂"]},
    {"name": "瑞思拜", "aliases": ["respect"], "category": "表达敬意", "meaning": "Respect 的音译，表示佩服。", "origin": "综艺《中国新说唱》带火。", "usage": "佩服某人操作/态度时用。", "example": "这老哥真能折腾，瑞思拜", "related": ["respect"]},
    {"name": "泰裤辣", "aliases": ["太酷啦"], "category": "音乐/偶像", "meaning": "“太酷了”的空耳，带中二感。", "origin": "小鬼王琳凯活动现场发言被网友空耳。", "usage": "夸张表达酷、帅，常带调侃。", "example": "刚看我朋友用Arch装机成功，泰裤辣", "related": ["太酷了"]},
    {"name": "显眼包", "aliases": ["显眼包本包"], "category": "人物评价", "meaning": "形容爱出风头、在哪都很抢眼的人，褒贬看语境。", "origin": "方言词汇经网络放大。", "usage": "朋友间调侃爱秀的人。", "example": "全场最显眼包的就是他了", "related": ["出风头"]},
    {"name": "搭子", "aliases": ["饭搭子", "游戏搭子"], "category": "社交", "meaning": "一起做某件事的固定同伴，吃饭/游戏/健身都可。", "origin": "2023年职场社交热词。", "usage": "找同伴时用，比朋友轻量。", "example": "找个游戏搭子一起联机种田", "related": ["拼单"]},
    {"name": "多巴胺穿搭", "aliases": ["多巴胺"], "category": "时尚", "meaning": "穿亮色系衣服让自己和他人开心，主打鲜艳配色。", "origin": "2023年穿搭博主带火。", "usage": "形容色彩大胆的穿搭风格。", "example": "今天这身多巴胺穿搭，看着就心情好", "related": ["美拉德"]},
    {"name": "电子榨菜", "aliases": ["电子下饭菜"], "category": "生活方式", "meaning": "吃饭时配着看的短视频/综艺/剧，像下饭菜。", "origin": "网络对“吃饭必须看点什么”现象的总结。", "usage": "指那些不用动脑、适合下饭的内容。", "example": "这部下饭综艺就是我今天的电子榨菜", "related": ["下饭"]},
    {"name": "遥遥领先", "aliases": ["YYDS"], "category": "科技/手机", "meaning": "形容远超对手，源自华为发布会余承东高频台词。", "origin": "华为发布会还有网友用“遥遥领先”刷屏。", "usage": "夸产品/技术领先，或反讽吹牛。", "example": "这波AI性能直接遥遥领先", "related": ["华为"]},
    {"name": "硬控", "aliases": ["被硬控"], "category": "游戏/网络", "meaning": "被某事物彻底吸引、动弹不得。", "origin": "游戏术语“硬控”引申到生活。", "usage": "看到好看/离谱内容走不动道。", "example": "被这个视频硬控了三分钟", "related": ["上头"]},
    {"name": "泼天的富贵", "aliases": ["泼天富贵"], "category": "好运", "meaning": "形容天大的好运或财富突然降临。", "origin": "网友自嘲/祝福语，2023年起爆火。", "usage": "接好运或羡慕别人暴富。", "example": "这波泼天的富贵终于轮到我了", "related": ["锦鲤"]},
    {"name": "脆皮大学生", "aliases": ["脆皮"], "category": "校园", "meaning": "调侃体质弱、容易受伤/生病的大学生。", "origin": "大学生分享各种离谱受伤经历走红。", "usage": "形容年轻人身体脆，也自我调侃。", "example": "一个喷嚏把腰闪了，脆皮大学生实锤", "related": ["大学生"]},
    {"name": "麦门", "aliases": ["麦当劳门徒"], "category": "饮食", "meaning": "“麦当劳教”的梗，表示对麦当劳的热爱。", "origin": "网友把“麦当劳”比作信仰，回应“麦门”。", "usage": "聊麦当劳/接梗时使用。", "example": "麦门，今天吉士堡又缩水了但还是要吃", "related": ["麦当劳"]},
    {"name": "你在教我做事啊", "aliases": ["你在教我做事"], "category": "怼人", "meaning": "反驳别人多管闲事、指点自己。", "origin": "影视台词/短视频梗。", "usage": "半开玩笑半认真怼指手画脚的人。", "example": "你别说了，你在教我做事啊", "related": ["关你什么事"]},
    {"name": "啊对对对", "aliases": ["对对对"], "category": "敷衍", "meaning": "敷衍式认同，实际懒得争辩。", "origin": "网友用来终结争论的万能回复。", "usage": "不想吵又不想理时用。", "example": "啊对对对，你说得都对", "related": ["你说得对"]},
    {"name": "退退退", "aliases": ["退退退退退"], "category": "网络段子", "meaning": "用手势和口头禅驱赶不祥/讨厌的事物。", "origin": "大妈驱赶摆摊者视频走红。", "usage": "对糟心事、烂广告、坏运气喊退退退。", "example": "摇一摇广告给我退退退", "related": ["驱邪"]},
    {"name": "芭比Q", "aliases": ["完犊子", "barbecue"], "category": "悲惨", "meaning": "完蛋了、凉了，源自英文 barbecue 谐音。", "origin": "主播“迷人的郭老师”带火。", "usage": "搞砸事情后的自嘲。", "example": "系统被我搞挂了，芭比Q了", "related": ["完蛋"]},
    {"name": "栓Q", "aliases": ["thank you"], "category": "感谢", "meaning": "Thank you 的音译，带土味幽默。", "origin": "广西农民英语教学视频走红。", "usage": "搞笑地表达感谢。", "example": "栓Q，这波教程太有用了", "related": ["谢谢"]},
    {"name": "奥利给", "aliases": ["奥利给干就完了"], "category": "加油", "meaning": "加油打气，阳刚雄壮。", "origin": "快手上的健身主播“冬泳怪鸽”经典台词。", "usage": "给自己或别人打气。", "example": "奥利给，今天一定把问题修好", "related": ["加油"]},
    {"name": "老铁", "aliases": ["铁子"], "category": "称呼", "meaning": "兄弟/朋友，东北口语经直播平台放大。", "origin": "快手直播常用称呼。", "usage": "拉近关系用。", "example": "老铁没毛病，双击666", "related": ["兄弟"]},
    {"name": "集美", "aliases": ["姐妹们"], "category": "称呼", "meaning": "姐妹的谐音，女性网友互称。", "origin": "博主“迷人的郭老师”带火。", "usage": "女性社交圈称呼。", "example": "集美们，这个坑我替你们踩过了", "related": ["姐妹"]},
    {"name": "无语子", "aliases": ["无语凝噎"], "category": "情绪", "meaning": "无语到了极点。", "origin": "网络常用后缀“子”卖萌化。", "usage": "对离谱事表示无语。", "example": "无语子，开机又蓝屏", "related": ["无语"]},
    {"name": "绝绝子", "aliases": ["绝了"], "category": "夸奖", "meaning": "太绝了、太好/太差到极致。", "origin": "饭圈/网红带货带火。", "usage": "夸张评价，褒贬自由。", "example": "这个主题配色绝绝子", "related": ["绝了"]},
    {"name": "yyds", "aliases": ["永远的神"], "category": "夸奖", "meaning": "永远的神，最高赞美。", "origin": "电竞圈，后全网通用。", "usage": "夸人/物顶尖。", "example": "开源社区永远滴神", "related": ["最强"]},
    {"name": "emo", "aliases": ["我emo了"], "category": "情绪", "meaning": "情绪低落、伤感。", "origin": "Emotional 缩写，网络流行。", "usage": "表达难过、空虚。", "example": "夜深了突然有点emo", "related": ["破防"]},
    {"name": "破防", "aliases": ["破大防"], "category": "情绪", "meaning": "心理防线被击穿，或感动或破防。", "origin": "游戏“破防”引申为情绪崩溃。", "usage": "被触动/被气到绷不住时用。", "example": "看到那个回滚脚本的教程，我直接破防", "related": ["绷不住"]},
    {"name": "摆烂", "aliases": ["摆烂人生"], "category": "态度", "meaning": "破罐破摔，不努力了。", "origin": "NBA摆烂文化传入中文网络。", "usage": "自嘲放弃挣扎。", "example": "这bug修不动了，先摆烂再说", "related": ["躺平"]},
    {"name": "摸鱼", "aliases": ["划水"], "category": "职场", "meaning": "上班/学习时偷懒。", "origin": "四川方言“摸鱼”网络化。", "usage": "形容不干活。", "example": "这周摸鱼摸得飞起", "related": ["划水"]},
    {"name": "内卷", "aliases": ["卷"], "category": "社会", "meaning": "恶性竞争，大家更努力但产出没变。", "origin": "学术圈“内卷”概念普及。", "usage": "形容无意义竞争。", "example": "这行太卷了，还是折腾Linux快乐", "related": ["卷王"]},
    {"name": "躺平", "aliases": ["躺平学"], "category": "态度", "meaning": "不争不抢、降低欲望从容生活。", "origin": "2021年网络热词。", "usage": "表达低欲望生活态度。", "example": "想躺平了，折腾不动了", "related": ["摆烂"]},
    {"name": "爷青回", "aliases": ["青春回来了"], "category": "怀旧", "meaning": "爷的青春回来了，经典再现。", "origin": "B站弹幕文化。", "usage": "看到老内容/老游戏回归时刷。", "example": "看到老版桌面又回来了，爷青回", "related": ["爷青结"]},
    {"name": "社死", "aliases": ["社会性死亡"], "category": "尴尬", "meaning": "当众出丑到不敢见人。", "origin": "网络热词，指名誉扫地。", "usage": "形容极度尴尬场面。", "example": "讲课PPT放错文件，直接社死", "related": ["尴尬"]},
    {"name": "挖呀挖呀挖", "aliases": ["挖挖挖"], "category": "儿歌/洗脑", "meaning": "幼儿手指谣《花园种花》走红，被全年龄段翻唱。", "origin": "2023年幼儿园老师视频爆火。", "usage": "玩梗/洗脑循环。", "example": "在小小的电脑里挖呀挖呀挖，装大大的系统", "related": ["花园种花"]},
    {"name": "科目三", "aliases": ["广西科目三"], "category": "舞蹈", "meaning": "源自广西的魔性舞蹈，后全球流行。", "origin": "“广西人必备三项技能”的网络段子。", "usage": "指魔性扭胯舞，也用于玩梗。", "example": "赢了比赛奖励一支科目三", "related": ["恐龙扛狼"]},
    {"name": "恐龙扛狼", "aliases": ["扛狼扛狼扛"], "category": "洗脑", "meaning": "“这是什么鬼”的空耳，魔性节奏。", "origin": "云南主播翻唱视频走红。", "usage": "表惊叹/无法理解。", "example": "这波操作恐龙扛狼扛狼扛", "related": ["什么鬼"]},
    {"name": "蓝瘦香菇", "aliases": ["蓝瘦", "香菇"], "category": "难受", "meaning": "“难受想哭”的广西口音谐音。", "origin": "2016年广西小伙失恋视频走红。", "usage": "自嘲难受。", "example": "电脑又坏了，蓝瘦香菇", "related": ["难受"]},
    {"name": "雨女无瓜", "aliases": ["与你无瓜"], "category": "怼人", "meaning": "“与你无关”的谐音卖萌版。", "origin": "《巴啦啦小魔仙》游乐王子口音。", "usage": "拒绝别人管闲事。", "example": "我修不修系统，雨女无瓜", "related": ["与你无关"]},
    {"name": "干饭人", "aliases": ["干饭魂"], "category": "饮食", "meaning": "吃饭积极、干饭至上的人。", "origin": "“干饭人干饭魂”口号走红。", "usage": "自嘲爱吃/到点吃饭。", "example": "干饭人干饭魂，饭点到了", "related": ["打工人"]},
    {"name": "打工人", "aliases": ["打工人打工魂"], "category": "职场", "meaning": "职场人自嘲，带苦中作乐。", "origin": "2020年“打工人”语录走红。", "usage": "自嘲上班族。", "example": "打工人今天也在摸鱼和搬砖之间反复横跳", "related": ["尾款人"]},
    {"name": "尾款人", "aliases": ["尾款人尾款魂"], "category": "消费", "meaning": "电商大促期间付尾款的人，自嘲钱包空。", "origin": "双十一购物节网络梗。", "usage": "调侃购物花超预算。", "example": "尾款人昨晚付完尾款，今天吃土", "related": ["剁手"]},
    {"name": "欧皇", "aliases": ["欧洲人"], "category": "运气", "meaning": "运气爆棚的人。", "origin": "抽卡游戏血统论。", "usage": "抽到好东西时夸人。", "example": "十连双金，真欧皇", "related": ["非酋"]},
    {"name": "非酋", "aliases": ["非洲人"], "category": "运气", "meaning": "运气极差的人。", "origin": "抽卡游戏血统论。", "usage": "自嘲抽卡手黑。", "example": "连歪三次，非酋本酋", "related": ["欧皇"]},
    {"name": "白嫖", "aliases": ["白嫖党"], "category": "消费", "meaning": "不花钱享受服务/内容。", "origin": "网络用语，原指嫖客不付费。", "usage": "自嘲/调侃免费用东西。", "example": "开源软件就是用来白嫖的，感谢开发者", "related": ["免费"]},
    {"name": "赛博", "aliases": ["cyber"], "category": "前缀", "meaning": "网络/数字/电子相关的造词前缀。", "origin": "Cyberpunk 等科幻文化。", "usage": "加在词前表示数字化。", "example": "赛博茶馆，线上喝茶聊天", "related": ["电子"]},
    {"name": "典中典", "aliases": ["典"], "category": "吐槽", "meaning": "非常典型、极具代表性，常用作反讽。", "origin": "“经典”的强化版，B站评论常用。", "usage": "遇到教科书般的骚操作/言论时刷。", "example": "把系统更新搞崩然后骂Linux，典中典", "related": ["经典"]},
    {"name": "绷不住", "aliases": ["蚌埠住了"], "category": "情绪", "meaning": "忍不住笑/哭。", "origin": "“绷不住”口语，谐音“蚌埠住了”。", "usage": "看到好笑/离谱内容。", "example": "看到你的操作，我蚌埠住了", "related": ["破防"]},
    {"name": "已老实", "aliases": ["求放过"], "category": "认怂", "meaning": "认怂、服了、不敢了。", "origin": "网络求饶梗，常配合表情包。", "usage": "被搞怕了求放过。", "example": "已老实，求系统别崩了", "related": ["求放过"]},
    {"name": "精神状态良好", "aliases": ["精神状态美丽"], "category": "反讽", "meaning": "反讽精神状态其实不好。", "origin": "年轻人自嘲语录。", "usage": "被折磨到麻木时自报状态。", "example": "连续加班一周，精神状态良好（才怪）", "related": ["疯球了"]},
    {"name": "我的沉默震耳欲聋", "aliases": ["沉默是金"], "category": "无语", "meaning": "无语到极致，沉默表达强烈态度。", "origin": "网络金句。", "usage": "对离谱言论不想回话时。", "example": "看到这个需求文档，我的沉默震耳欲聋", "related": ["无语"]},
    {"name": "你说的都对", "aliases": ["你说得对"], "category": "敷衍", "meaning": "表面认同实为敷衍/反讽。", "origin": "万能聊天糊弄学。", "usage": "不想争辩时。", "example": "你说的都对，我选择沉默", "related": ["啊对对对"]},
    {"name": "舔狗", "aliases": ["舔狗一无所有"], "category": "人物评价", "meaning": "卑微讨好对方的人，多指单方面付出。", "origin": "网络流行语。", "usage": "自嘲或调侃他人。", "example": "别当舔狗，直接上真本事", "related": ["备胎"]},
    {"name": "小丑竟是我自己", "aliases": ["小丑"], "category": "自嘲", "meaning": "发现自己才是那个搞笑/尴尬的人。", "origin": "小丑表情包+电影梗。", "usage": "自嘲被现实打脸。", "example": "以为稳赢，结果小丑竟是我自己", "related": ["破防"]},
    {"name": "天花板", "aliases": ["天花板级别"], "category": "夸奖", "meaning": "顶尖、最高水准。", "origin": "“XX的天花板”句式流行。", "usage": "夸人/物达到顶配。", "example": "这是Linux桌面折腾的天花板", "related": ["顶级"]},
    {"name": "降维打击", "aliases": ["降维打击"], "category": "比较", "meaning": "用绝对优势碾压对手，源自《三体》。", "origin": "《三体》概念网络化。", "usage": "形容实力碾压。", "example": "新模型一出来，老方案直接被降维打击", "related": ["碾压"]},
    {"name": "活久见", "aliases": ["活得久了什么都能见到"], "category": "感叹", "meaning": "活得久什么都能见到，表惊叹罕见事。", "origin": "网络感叹语。", "usage": "遇到罕见/离谱事。", "example": "活久见，Windows居然主动推送Linux教程", "related": ["离谱"]},
    {"name": "键盘侠", "aliases": ["网络喷子"], "category": "人物评价", "meaning": "在网上指点江山、嘴炮很凶的人。", "origin": "网络批判现象。", "usage": "形容只会在网上喷的人。", "example": "键盘侠在评论区输出，代码一行不会写", "related": ["杠精"]},
    {"name": "杠精", "aliases": ["杠精本精"], "category": "人物评价", "meaning": "喜欢抬杠、为杠而杠的人。", "origin": "网络流行语。", "usage": "形容无理反驳的人。", "example": "这都能杠，真杠精", "related": ["抬杠"]},
    {"name": "塌房", "aliases": ["房子塌了"], "category": "饭圈", "meaning": "偶像人设崩塌、粉丝心碎。", "origin": "饭圈用语出圈。", "usage": "偶像出丑闻时用。", "example": "又塌房了，这次房倒得彻底", "related": ["人设崩塌"]},
    {"name": "实锤", "aliases": ["石锤"], "category": "吃瓜", "meaning": "确凿证据实锤。", "origin": "网络八卦用语。", "usage": "证据坐实时用。", "example": "聊天记录都放出来了，实锤", "related": ["石锤"]},
    {"name": "营业", "aliases": ["营业中"], "category": "饭圈", "meaning": "偶像/账号上线发内容、互动。", "origin": "饭圈用语。", "usage": "指按时发内容/出现。", "example": "终于营业了，等你好久", "related": ["摸鱼"]},
    {"name": "带薪拉屎", "aliases": ["带薪摸鱼"], "category": "职场", "meaning": "上班时偷懒摸鱼。", "origin": "职场自嘲梗。", "usage": "调侃上班摸鱼。", "example": "带薪拉屎是打工人最后的倔强", "related": ["摸鱼"]},
    {"name": "职场PUA", "aliases": ["PUA"], "category": "职场", "meaning": "上级通过打压、贬低控制下属。", "origin": "PUA 概念从恋爱圈进入职场。", "usage": "批评不良管理。", "example": "天天被职场PUA，人快没了", "related": ["精神控制"]},
    {"name": "996", "aliases": ["996ICU"], "category": "职场", "meaning": "早9晚9一周6天的工作制。", "origin": "程序员群体抗议加班文化。", "usage": "批评过劳工作。", "example": "996干久了，身体先报警", "related": ["007"]},
    {"name": "三和大神", "aliases": ["三和"], "category": "社会", "meaning": "深圳三和人才市场附近打零工、躺平的年轻人。", "origin": "社会新闻/纪录片走红。", "usage": "形容低欲望打零工生活。", "example": "活成了三和大神，一天一结", "related": ["躺平"]},
    {"name": "脱不下长衫", "aliases": ["孔乙己的长衫"], "category": "社会", "meaning": "学历束缚，放不下身段做底层工作。", "origin": "孔乙己梗2023年被热议。", "usage": "自嘲高不成低不就。", "example": "脱不下长衫，又找不到好工作", "related": ["孔乙己"]},
    {"name": "特种兵旅游", "aliases": ["特种兵式旅游"], "category": "旅游", "meaning": "极限时间打卡多个景点的密集型旅游。", "origin": "大学生旅游方式走红。", "usage": "形容行程极满的旅游。", "example": "周末特种兵旅游，一天逛了八个景点", "related": ["旅游"]},
    {"name": "淄博烧烤", "aliases": ["进淄赶烤"], "category": "文旅", "meaning": "淄博烧烤火爆带动文旅热。", "origin": "2023年淄博烧烤出圈。", "usage": "指烧烤热/城市文旅现象。", "example": "进淄赶烤，这辈子值了", "related": ["烧烤"]},
    {"name": "南方小土豆", "aliases": ["小土豆"], "category": "地域", "meaning": "东北人对南方游客的昵称，形容个子娇小可爱。", "origin": "哈尔滨文旅热中的称呼。", "usage": "形容南方游客（带宠溺）。", "example": "南方小土豆勇闯冰雪大世界", "related": ["砂糖桔"]},
    {"name": "砂糖桔", "aliases": ["广西砂糖桔"], "category": "地域", "meaning": "广西小朋友游学团的昵称，因统一穿橘色衣服像砂糖桔。", "origin": "哈尔滨文旅热中的称呼。", "usage": "形容穿橙色衣服的小朋友游客。", "example": "砂糖桔大军下场了，自带萌点", "related": ["南方小土豆"]},
    {"name": "赛博养生", "aliases": ["电子养生"], "category": "生活方式", "meaning": "用科技产品/App养生，比如保温杯泡枸杞+智能手环。", "origin": "年轻人自嘲养生方式。", "usage": "调侃边熬夜边养生的矛盾。", "example": "戴着手环熬夜监控心率，赛博养生了属于是", "related": ["朋克养生"]},
    {"name": "数字生命", "aliases": ["数字永生"], "category": "科幻", "meaning": "把意识/记忆数字化延续生命。", "origin": "科幻概念+流浪地球讨论。", "usage": "科幻/哲学话题用。", "example": "数字生命也就是把记忆上传，离永生还远着呢", "related": ["赛博"]},
    {"name": "炼丹", "aliases": ["炼丹师"], "category": "AI", "meaning": "训练AI模型的戏称，调参像炼丹。", "origin": "AI圈自嘲。", "usage": "形容训练模型、调参。", "example": "今晚又要炼丹，9B模型可没那么好伺候", "related": ["大模型"]},
    {"name": "大模型", "aliases": ["LLM"], "category": "AI", "meaning": "大规模语言模型，泛指AI对话/生成模型。", "origin": "AI热潮词汇。", "usage": "AI领域日常用。", "example": "大模型再强，也得吃饭喝水……哦它不用喝水", "related": ["AI"]},
    {"name": "屎山代码", "aliases": ["屎山"], "category": "编程", "meaning": "结构混乱、难维护的代码。", "origin": "程序员自嘲。", "usage": "吐槽烂代码。", "example": "接手十年屎山，每天在火葬场上班", "related": ["重构"]},
    {"name": "喂屎", "aliases": ["喂shit"], "category": "吐槽", "meaning": "给用户/观众输出垃圾内容。", "origin": "网络吐槽语。", "usage": "批评低质内容。", "example": "开机广告喂屎就算了，还摇一摇", "related": ["辣鸡"]},
    {"name": "遇事不决量子力学", "aliases": ["量子力学"], "category": "玩梗", "meaning": "遇到解释不了的事就甩给量子力学，万能解。", "origin": "B站科普/弹幕文化。", "usage": "对魔幻现象表示放弃解释。", "example": "为什么重启一下就好了？遇事不决量子力学", "related": ["玄学"]},
]