# -*- coding: utf-8 -*-
"""补充一批 Linux agent 轨迹样本（第二轮训练用，不动当前训练读的文件）。
覆盖：多命令行管道、DNS/时间、挂载、权限、容器、cron、压缩、文本处理等。
"""

from agent_toolformat import agent_sample

EXTRA_SAMPLES = [
    # ---- DNS 解析排查 ----
    agent_sample(
        "dns-issue", "解析域名失败的排查",
        "我访问网站特别慢，有时候直接解析不出来，帮我看下DNS",
        [
            ("tool_call", {"thinking": "先看系统 DNS 配置和能否解析，再试公共 DNS 对比", "command": "cat /etc/resolv.conf && echo '---' && getent hosts archlinux.org && echo '---' && systemd-resolve --status 2>/dev/null | head -5 || resolvectl status | head -5"}),
            ("tool_result", "# Generated by NetworkManager\nnameserver 192.168.1.1\n---\n（getent 无输出，解析失败）\n---\nCurrent DNS Server: 192.168.1.1\nDNS Domain: lan\n"),
            ("tool_call", {"thinking": "路由器 DNS 解析失败，换公共 DNS 验证是不是上游问题", "command": "echo 'nameserver 223.5.5.5' > /tmp/test_resolv && resolvectl dns wlan0 223.5.5.5 2>/dev/null; getent hosts archlinux.org"}),
            ("tool_result", "198.25.188.30（换成阿里 DNS 后解析成功）"),
            ("assistant", "定位了：是你家路由器 192.168.1.1 的 DNS 解析不了，换成阿里公共 DNS 223.5.5.5 立就能通了。建议进路由器把 DNS 填成 223.5.5.5 和 119.29.29.29，或者在 NetworkManager 里给 wlan0 固定这两个 DNS，别用你路由器的"),
        ],
    ),

    # ---- 系统时间/时钟漂移 ----
    agent_sample(
        "clock-drift", "系统时间不对",
        "我系统时间总是不对，比实际慢了几分钟",
        [
            ("tool_call", {"thinking": "先看当前时间、时区和 NTP 状态，判断是时区错还是漂移", "command": "date && timedatectl && echo '---' && cat /etc/adjtime"}),
            ("tool_result", "Wed 2026-08-21 01:22:34 CST\n     Local time: ... CST\n     Universal: 2026-08-20 17:22:34 UTC\n     NTP service: inactive\n     RTC: local\n（本地时间 CST 看起来对，但 NTP 没开）"),
            ("tool_call", {"thinking": "NTP 没启用，开启时间同步服务并立即校准", "command": "sudo systemctl enable --now systemd-timesyncd && sudo timedatectl set-ntp true && sleep 3 && timedatectl"}),
            ("tool_result", "     NTP service: active\n     Local time: correct 同步完成\n     RTC: local"),
            ("assistant", "搞定了。你之前 NTP 没开，系统时间靠自己漂移越走越偏。现在我开了 systemd-timesyncd 自动同步，也会开机自启，以后不会再偏了。另外注意 RTC 是 local 模式，你要是还装 Windows 双系统记得保持一致，不然会两个系统互相改时间"),
        ],
    ),

    # ---- 挂载 USB / 权限 ----
    agent_sample(
        "mount-usb", "挂载 U 盘",
        "我插了U盘，但访问不了里面的文件",
        [
            ("tool_call", {"thinking": "先看 U 盘在哪个块设备、有没有自动挂载、挂在哪", "command": "lsblk -o NAME,SIZE,FSTYPE,MOUNTPOINT && echo '---' && ls /media/ /run/media/$(whoami)/ 2>/dev/null"}),
            ("tool_result", "sdb1  28G  vfat\n（sdb1 没挂载点说明没自动挂上）"),
            ("tool_call", {"thinking": "U 盘是 vfat，手动挂载到 /mnt/usb", "command": "sudo mkdir -p /mnt/usb && sudo mount -o uid=$(id -u),gid=$(id -g) /dev/sdb1 /mnt/usb && ls -l /mnt/usb | head"}),
            ("tool_result", "文件列表正常显示（部分 .jpg、.doc、.tar.gz）"),
            ("assistant", "U 盘没自动挂载，我手动挂到 /mnt/usb 了，现在能正常读。拷完文件记得先 sudo umount /mnt/usb 再拔，别直接拔，vfat 容易丢数据。要设成插上自动挂载的话我可以帮你配 udisks2"),
        ],
    ),

    # ---- 修复文件权限 ----
    agent_sample(
        "fix-perm", "修复 Web 目录权限",
        "我的网站目录被搞坏了权限，访问报 403",
        [
            ("tool_call", {"thinking": "先看目录当前权限和所属用户，判断是权限还是属主问题", "command": "ls -ld /srv/www && ls -l /srv/www | head -3 && stat -c '%a %U %G' /srv/www"}),
            ("tool_result", "drwxr-xr-x 3 root root /srv/www\n（root 所有，普通进程访问不到）"),
            ("tool_call", {"thinking": "访客进程以 http 用户跑，把目录属主改成 http 并给正确的读取权限", "command": "sudo chown -R http:http /srv/www && sudo chmod -R u=rwX,go=rX /srv/www && sudo -u http ls /srv/www | head"}),
            ("tool_result", "list 成功，403 应该解决了"),
            ("assistant", "权限修好了：之前目录是 root 所有的，Web 进程（http 用户）读不了才报 403。我改成 http:http 属主 + 标准可读权限，现在能正常访问了。以后别再把网站目录设成 root 属主或 777，安全"),
        ],
    ),

    # ---- 容器管理 ----
    agent_sample(
        "docker-clean", "清理 Docker 无用资源",
        "我的 Docker 占了太多磁盘，帮清理一下",
        [
            ("tool_call", {"thinking": "先看 docker 到底占了多少、有没有停掉的容器和悬空镜像，再决定清什么", "command": "docker system df && docker ps -a --format '{{.Names}} {{.Status}}' | head"}),
            ("tool_result", "TYPE  TOTAL  ACTIVE  SIZE  RECLAIMABLE\nImages  28  5  3.2GB  2.1GB\nContainers  31  4  810MB  780MB\nBuild Cache  1.1GB  1.1GB\n（5个停掉容器、23个悬空镜像、构建缓存）"),
            ("tool_call", {"thinking": "这些都是可回收的：停掉的容器、悬空镜像、构建缓存。先列出来再清", "command": "docker container prune -f && docker image prune -f && docker builder prune -f && docker system df"}),
            ("tool_result", "Deleted Containers: 5, Deleted Images: 18, 构建缓存已清\nRECLAIMABLE 从 4GB 降到 200MB"),
            ("assistant", "清完了，回收了约 4G：5 个停掉的容器、18 个悬空镜像、1.1G 构建缓存。你还在跑的那 4 个容器和 5 个镜像一个没动。想彻底清（包括没在用的数据卷）得你自己确认，那东西可能有数据我不擅自删，要清说一声"),
        ],
    ),

    # ---- 设置 cron 定时任务 ----
    agent_sample(
        "cron-backup", "设置每日定时备份",
        "帮我把 /home/user/docs 每天凌晨2点备份到 /backup",
        [
            ("tool_call", {"thinking": "先确认目标目录存在，然后用 crontab 加一条 rsync 备份任务", "command": "ls -d /home/user/docs /backup 2>&1; which rsync; crontab -l 2>/dev/null || echo no-crontab"}),
            ("tool_result", "/home/user/docs\n/backup\n/usr/bin/rsync（目录都在，rsync 也装了））"),
            ("tool_call", {"thinking": "目录和 rsync 就绪，追加每天 02:00 的备份计划", "command": "(crontab -l 2>/dev/null; echo '0 2 * * * rsync -a --delete /home/user/docs/ /backup/docs/ >> /backup/docs_backup.log 2>&1') | crontab - && crontab -l | tail -2"}),
            ("tool_result", "0 2 * * * rsync -a --delete /home/user/docs/ /backup/docs/ >> /backup/docs_backup.log 2>&1（已写入）"),
            ("assistant", "定时任务建好了：每天凌晨 2 点用 rsync 把 /home/user/docs 增量备份到 /backup/docs/，日志记在 backup 里。--delete 是让目标跟源一致，删除的文件也会同步删——如果你希望保留被删的旧版本，告诉我，我换 --delete 掉用带时间戳的归档方式"),
        ],
    ),

    # ---- 压缩解压 ----
    agent_sample(
        "untar", "解压并查看 tar.gz 内容",
        "帮我解压这个 research.tar.gz，先看下里面有什么",
        [
            ("tool_call", {"thinking": "先列出 tarball 内容确认结构，再决定解压到哪", "command": "tar -tzf research.tar.gz | head -20 && du -h research.tar.gz"}),
            ("tool_result", "research/\nresearch/report.pdf\nresearch/data/*.csv\n（根目录是 research/ 文件夹，不会散一地）"),
            ("tool_call", {"thinking": "结构干净，直接解压", "command": "tar -xzf research.tar.gz && ls -l research/"}),
            ("tool_result", "report.pdf  data/  notes.md（解压完成）"),
            ("assistant", "解压好了，文件都在 research/ 目录下，报告、数据、笔记都在。源 tarball 我先没删，确认没问题要清理的话我帮你处理"),
        ],
    ),

    # ---- 批量文本处理 ----
    agent_sample(
        "sed-find", "批量替换文本",
        "把项目里所有 .txt 里的 oldname 全改成 newname",
        [
            ("tool_call", {"thinking": "先确认有多少 txt、替换会不会误伤，再动手", "command": "grep -rl 'oldname' --include='*.txt' . | wc -l && grep -rl 'oldname' --include='*.txt' . | head"}),
            ("tool_result", "3 个文件包含 oldname\n（3 个文件）"),
            ("tool_call", {"thinking": "只有 3 个 txt，确认范围后用 sed 就地替换", "command": "grep -rl 'oldname' --include='*.txt' . | xargs sed -i 's/oldname/newname/g' && grep -rL 'oldname' --include='*.txt' . | wc -l && echo '替换检查：' && grep -rl 'new​name' --include='*.txt' . | head"}),
            ("tool_result", "替换完成，3 个文件里的 oldname 都已改成 newname，已无残留 oldname"),
            ("assistant", "改好了，3 个 txt 里的所有 oldname 都换成了 newname，我又确认了一遍没有残留。原文件是直接覆盖改的（sed -i 就地改），要是想留备份告诉我，下次用 sed -i.bak 会帮你存一份 .bak"),
        ],
    ),

    # ---- 安装驱动/内核模块 ----
    agent_sample(
        "kernel-module", "加载并测试内核模块",
        "帮我加载一下 v4l2loopback 这个内核模块",
        [
            ("tool_call", {"thinking": "先看模块装没装、当前加载没有", "command": "modinfo v4l2loopback >/dev/null 2>&1 && echo '已安装' || echo '未安装'; lsmod | grep v4l2loopback || echo '未加载'"}),
            ("tool_result", "已安装\n未加载"),
            ("tool_call", {"thinking": "模块已装但没加载，modprobe 加载并确认", "command": "sudo modprobe v4l2loopback && lsmod | grep v4l2loopback"}),
            ("tool_result", "v4l2loopback  18432  0（已加载）"),
            ("assistant", "v4l2loopback 已经加载好了。注意这是临时加载，重启就没了。要开机自动加载的话，echo 'v4l2loopback' | sudo tee /etc/modules-load.d/v4l2loopback.conf，我帮你加？"),
        ],
    ),
]
